version: "3.8"

services:
  pi-stats:
    build:
      context: ./
    container_name: pi-stats
    ports:
      - '3000:3000'
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge

