
services:

  pi-stats:
    build:
      context: ./
    container_name: pi-stats
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-net

networks:
  app-net:
    name: ${CONTAINER_NETWORK:-app-net}
    external: true

