
services:
  pi-stats:
    build:
      context: ./
    container_name: pi-stats
    ports:
      - '3000:3000'
    restart: always
    networks:
      - bridge

networks:
  bridge:
    name: "bridge"
    driver: bridge
    external: true

